# Generated by Django 5.1.7 on 2025-04-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
